### PR TITLE
add move in left transition

### PR DESCRIPTION
**Pull request by saileshbro**

### CODE REVIEW

**Review by FilledStacks — CHANGES_REQUESTED** [review]
Please remove the version changes for this since it's a bit out dated

**Comment by saileshbro** [comment]
@FilledStacks I've made the changes

**Comment by FilledStacks** [comment]
@eb-so I like this PR. Could we add this transition into our transitions and close this PR since it's very old and has many conflicts.

**Comment by eb-so** [comment]
@FilledStacks @saileshbro Replaced by #609

**Pull request closed without merging**
