### PR TITLE
Feat/close snackbar

### PR DESCRIPTION
**Pull request by dvagala**
There can be scenarios where you want to programatically close the current snackbar.
* The message is no longer relevant, e.g.: you show 'no connection warning' and in the meanwhile the device reconnected

### CODE REVIEW

**Comment by dvagala** [comment]
#719

**Comment by Eimen2018** [comment]
@FilledStacks LGTM

**Comment by Eimen2018** [comment]
@dvagala LGTM all that's left is package maintenance, please update the version and add a change log

**Comment by dvagala** [comment]
@Eimen2018 Done

**Comment by Eimen2018** [comment]
@dvagala unit tests are failing analyze is catching some deprecated param

**Comment by dvagala** [comment]
@Eimen2018 I see. I fixed the issue right now on separate pull requst #722 , since it's not releated to this. After that gets merged the checks in this pull request should be fine

**Comment by Eimen2018** [comment]
@dvagala You did an awesome work on the other PR, but you need to merge master here so that every test passes

**Comment by dvagala** [comment]
@Eimen2018 Sure no problem :) Now the test passed

**Pull request merged**
