### PR TITLE
fix(logger): call init/destroy methods for all outputs.

### LINKED ISSUE #884: [logger]: multi output logger should call "init" / "destroy" for each output.
The logger classes do support an "init"/"destroy" method.
When adding custom logger outputs (for example rolling file output),
the multi output logger should call init and destroy for all
inputs (they default to "noop").

### PR DESCRIPTION
**Pull request by buehler**
This fixes #884.

By utilizing [MultiOutput](https://github.com/Bungeefan/logger/blob/master/lib/src/outputs/multi_output.dart) of the logger package. The output calls init and destroy by default and
normalizes all outputs as well.

### CODE REVIEW

**Review by ferrarafer — COMMENTED** [review]
LGTM

**Review by FilledStacks — CHANGES_REQUESTED** [review]
I'm happy with the changes. @buehler if you can bump the `patch` version and add an entry into the changelog.md this can be merged and released 🚀

**Comment by FilledStacks** [comment]
@ferrarafer when the PR is updated you can merge and release the new version 😄  I'm signing off for the night.

**Comment by buehler** [comment]
Alright @ferrarafer @FilledStacks 
Did update the Changelog of the generator as well as the patch version.

Just saw that some tests are failing. Is this an issue of my changes? If so, I can try to fix them, but that'll need some time since I'm off for a few days.

**Comment by buehler** [comment]
Just skimmed through the tests, I'll fix them as soon as I get to it.

**Review by ferrarafer — APPROVED** [review]
Awesome !

**Comment by buehler** [comment]
Hey @ferrarafer 
I had a look at the tests. I fixed the ones related to my PR. The other four tests are not related to my PR as far as I know. I don't dare adjust some constant test values without knowing the system behind it. Wdyt about those tests? Apparently, the generator writes some `toString` method, that wasn't there before...

/cc @FilledStacks

**Comment by buehler** [comment]
Addition: it's been failing since https://github.com/FilledStacks/stacked/commit/5208cf416fece8ad9bcf7a283431c228bf45edc4

**Comment by ferrarafer** [comment]
@buehler I will fix the other tests and merge. It's a pleasure to see people collaborating on the project ❤️ , thank you!

**Comment by ferrarafer** [comment]
@buehler I fixed a few unit tests in your branch but I still see 3 unit tests failing on `SimpleLogPrinterTest`. Seems that we need to pass another argument. Can you fix them?
```
Error: Too few positional arguments: 4 required, 3 given.
final result = logger.log(LogEvent(Level.error, 'error', Exception('error')));
                                              ^
 ../../../../../.pub-cache/hosted/pub.dev/logger-1.1.0/lib/src/logger.dart:26:3: Context: Found this candidate, but the arguments don't match.
 LogEvent(this.level, this.message, this.error, this.stackTrace);
```

**Comment by buehler** [comment]
@ferrarafer happy to help with the project :-) it definitely makes flutter data management easy with the MVVM pattern :)

yea I'll check the test right away

**Comment by buehler** [comment]
@ferrarafer can you pinpoint the test for me? In my branch, they are working as they should (up to date with master)

**Comment by ferrarafer** [comment]
@buehler I'm getting the following errors. Push the changes I made in your branch to here and we will see if actions pass the checks.

1. test/logging/simple_log_printer_test.dart: SimpleLogPrinterTest - returns a correct log message.
2. test/logging/simple_log_printer_test.dart: SimpleLogPrinterTest - attaches the stacktrace if requested.
3. test/logging/simple_log_printer_test.dart: SimpleLogPrinterTest - prints error object if provided.

**Comment by buehler** [comment]
yea, happy to, where do I find the changes? I don't think you were able to make them in our repository in the smartive organization right?

**Comment by buehler** [comment]
ah... found them in the original repo... just a sec :)

**Comment by buehler** [comment]
Alright, had to fix a linter error, but now it seems to be working :-)
Thank you for the help @ferrarafer

**Comment by ferrarafer** [comment]
@buehler Great ❤️

**Pull request merged**
