### PR TITLE
📚 Add Documentation for Stacked Services!

### PR DESCRIPTION
**Pull request by YazeedAlKhalaf**
This pull request contains the following changes:
- Add New Documentation for `NavigationService` and `SnackbarService`.
- Some typos fixed.

The part of custom Snackbar is not written yet, because there is a todo about getting UI out like what you did with the dialog service. That's why I have left it. but whenever you finish the `showCustomSnackbar` and it is stable and no todos there, I will add the docs!

I hope it is helpful!

### CODE REVIEW

**Comment by YazeedAlKhalaf** [comment]
@FilledStacks

**Comment by FilledStacks** [comment]
@YazeedAlKhalaf Please add the a section that tells the dev that they have to set the navigation key on their material / cupertino app. They can do that using the key on the dialog service if they only want to use the dialog service or they can do that using the key on the navigation service. 

The key only has to be set once for it to work for all three services.

**Comment by FilledStacks** [comment]
I'll merge it in and fix it up now. I have some time

**Comment by YazeedAlKhalaf** [comment]
Thanks 💙

**Pull request merged**
