### PR TITLE
Add Text-To-Speech functionality by creating TtsService

### PR DESCRIPTION
**Pull request by YazeedAlKhalaf**
This PR has the following modifications:

• Added a new service to Stacked Services called `TtsService`, aka Text-To-Speech Service.
• Modified example app to show how the `TtsService` works by creating a new screen.
• Upgraded `minSdkVersion` to 21.

All those things are under one commit since they are related and would not make sense to make each one as a separate commit.

### CODE REVIEW

**Comment by YazeedAlKhalaf** [comment]
Are there any problems?

**Comment by FilledStacks** [comment]
I haven't looked at the code. I just finished the video, been busy with it today for the past 12 hours. I'll get back to open source code reviews tomorrow morning at 4:30 and I'll look at this too.

**Comment by YazeedAlKhalaf** [comment]
Okay that’s great to hear 👂

**Comment by FilledStacks** [comment]
@YazeedAlKhalaf this is not a fundamental service. It's not something that will be required by any basic mobile application so I can't add this dependency into the project is no one will be using this. This can be a separate package that you can maintain called stacked_tts and I'll feature it on the repo under the third party packages

**Comment by YazeedAlKhalaf** [comment]
Ah okay I got you 😉.

**Comment by YazeedAlKhalaf** [comment]
I will be making upgrades to the dialog service. There will be a choice for the dev to either use default material and Cupertino or the giffy_dialog.

😍

**Comment by YazeedAlKhalaf** [comment]
Okay I will be also making the package 📦 and make a new pull request 👌👌🥳

**Comment by FilledStacks** [comment]
@YazeedAlKhalaf that would be awesome. How far are you with the Material and Cupertino changes, I was going to work on that this week.

**Comment by YazeedAlKhalaf** [comment]
I am at the beginning but I have a question, do I start a new pull request or just push the code to my fork?

**Comment by YazeedAlKhalaf** [comment]
I will close this pull request and open a new one once I am done with the dialog service thing

**Comment by YazeedAlKhalaf** [comment]
I have implemented the Cupertino and material dialogs, still the Giffy dialog 👏🥳
@FilledStacks

**Comment by FilledStacks** [comment]
@YazeedAlKhalaf awesome. Just make sure those PR's are separate. Reviewing a big PR will take a lot of time from my side so I'll most likely split it over a week or two.

**Comment by YazeedAlKhalaf** [comment]
okay 👍

No worries. I deleted the old fork and started a new one just for this 👌

 I will be make the PR now!

**Comment by YazeedAlKhalaf** [comment]
@FilledStacks I have sent you some idea Whatsapp, I hope you can see it over there.

Now I have been done with the dialog service in terms of Material and Cupertino. The giffy dialog needs some more time and might not be easy to implement but I will try 👍

Will make the PR right now 😁😊🎉

**Pull request closed without merging**
