### PR TITLE
Removed `flutter_facebook_auth` dependency and its implementation

### PR DESCRIPTION
**Pull request by carlomigueldy**

### CODE REVIEW

**Review by FilledStacks — CHANGES_REQUESTED** [review]
The version isn't bumped in the `pubspec.yaml` file please change it to match the one in the Changelog

**Comment by carlomigueldy** [comment]
I've adjusted the version under `pubspec.yaml` and from the change log as well :)

**Review by FilledStacks — APPROVED** [review]
This had to be done. It was a terrible bug that was happening. We can add it back when the package allows for it all to be used together.

**Comment by merfire** [comment]
May I ask what happened here? Was this failing on iOS builds?
In my tests on Android, `MissingPluginException` only occurred when I explicitly called `signInWithFacebook()` function without configuration.

**Comment by FilledStacks** [comment]
@merfire this was removed because when you try to call google auth login you get a "not implemented exception" if facebook auth is not setup.

**Pull request merged**
