### PR TITLE
Added ability to set instance name in locator

### PR DESCRIPTION
**Pull request by zuboje**
This should allow setting up instanceName in the locator for moredetails take a look at [()](https://pub.dev/packages/get_it#experts-region)

### CODE REVIEW

**Review by FilledStacks — CHANGES_REQUESTED** [review]
Can I please see the generated output. I don't think this will compile when generated.

**Comment by zuboje** [comment]
@FilledStacks I will need your guidance to finish it. My app is not allowing me to use two plugins that depend one on another and they are both local it is requiring me for at least 1 plugin to be hosted, otherwise, it does not compile it, just throws an error during the build. How can I simultaneously test "Stacked" plugin changes and "stacked_generator" changes? Stacked changes are required because of the annotation, the generator uses the annotation. Can you please give me some guidance/link to some tutorial on how to test two plugins dependent one on another (generator depends on the stacked plugin)

**Comment by FilledStacks** [comment]
This has been added to the generator with the newest updates to add unit tests.

**Comment by eb-so** [comment]
Closes #584

**Pull request closed without merging**
