### PR TITLE
Rename `SelectorViewModelBuilderWidget` and `SelectorViewModelWidget` similar to `ViewModelWidget`

### PR DESCRIPTION
**Pull request by saileshbro**
- feat: add selector viewmodel builder
- chore: export widgets
- refactor: pass static child
- refactor: change implementation
- feat: add changelog, and bump version
- refactor: Rename `SelectorViewModelBuilderWidget` and `SelectorViewModelWidget` similar to `ViewModelWidget`

### CODE REVIEW

**Comment by saileshbro** [comment]
@FilledStacks i renamed the `SelectorViewModelBuilderWidget` to `SelectorViewModelWidget`. I think it makes more sense to make it `SelectorViewModelWidget` as it will be pretty similar to `ViewModelWidget`. What are your thoughts on this?
I can see a test failing with `stacked_generator` package.

**Review by FilledStacks — APPROVED** [review]
LGTM

**Comment by eb-so** [comment]
@saileshbro There is a failing test that can be fixed by merging with the master branch

**Comment by saileshbro** [comment]
@eb-so Tests passing, let's merge 🚀

**Pull request merged**
