### PR TITLE
Added finer error inspection

### PR DESCRIPTION
**Pull request by JohnnyRainbow81**
You can check the viewModel for hasAnyError() and currentError() now.

### CODE REVIEW

**Review by FilledStacks — CHANGES_REQUESTED** [review]
Awesome. 

You need to do the general housekeeping as well. 

- Update the patch version number
- Add an entry into the changelog for the new version number

**Comment by JohnnyRainbow81** [comment]
Heya...
@FilledStacks  could you please share some info on how to choose a patch version number? 
Cause this absolutely is my first time contributing to open source...

**Comment by eb-so** [comment]
@JohnnyRainbow81 Stacked versioning policy
For versioning a good guide is.

- When we collect a number of minor improvements and features we bump the major version
- When we implement new functionality we increase the minor version (second number)
- If we fix something or add to an existing implementation .i.e. add a new transition we increase the patch number (last digit)
- If no code changes or we only update configuration and the functionality of everything is still the same we add a +version

**Comment by JohnnyRainbow81** [comment]
Thank you @eb-so ! I'll investigate tonight, update the PR and then we can hopefully proceed.

**Pull request closed without merging**
