### PR TITLE
Added support for dynamic duration for snack bar.

### PR DESCRIPTION
**Pull request by vishhmakasana**
Duration field added in snackbar_config.dart so that we will not have to specify Duration on each show snackbar call.

### CODE REVIEW

**Review by FilledStacks — CHANGES_REQUESTED** [review]
This looks good. Lets get the conflicts fixed up then we can move forward on this.

**Comment by vishhmakasana** [comment]
> This looks good. Lets get the conflicts fixed up then we can move forward on this.

I am having a hard time finding those files, is it removed in the latest version of Stacked?

**Comment by FilledStacks** [comment]
@VishalMakasanaPep yes, they're in a different location now. Make sure you were on the latest when you forked for your PR.

**Comment by eb-so** [comment]
I need this to be merged, it's so annoying to add duration to each call
What can I do to help push this through?
@FilledStacks @ferrarafer

**Comment by vishhmakasana** [comment]
Deleting this PR as new PR is available for latest repo : https://github.com/Stacked-Org/services/pull/26

**Comment by ferrarafer** [comment]
> I need this to be merged, it's so annoying to add duration to each call
> 
> What can I do to help push this through?
> 
> @FilledStacks @ferrarafer 

I will merge the PR today, sorry for the delay, we were busy with the new site.

**Comment by eb-so** [comment]
@ferrarafer No worries, Thank you dude 🎊

**Pull request closed without merging**
