### PR TITLE
feat: adds custom object for keys in multiple stream view model

### PR DESCRIPTION
**Pull request by Afsal102**
issue: #504

### CODE REVIEW

**Comment by Afsal102** [comment]
cc: @Eimen2018

**Review by FilledStacks — CHANGES_REQUESTED** [review]
Hey, 

This will make it so that the multi stream viewmodel can only be used with one type. This is not how it's used in production. We use this to get multiple different type of stream results that we want to rebuild on screen. Not just a single type. 

You could instead make the StreamData generic, that should help with your type safety per stream viewmodel you want.

**Comment by Afsal102** [comment]
@FilledStacks oh, currently the key is string!, so even in production we still use one type!. am i missing something? 🤔 

> You could instead make the StreamData generic, that should help with your type safety per stream viewmodel you want

oh usually u will have only one type for Keys (currently its string(modified it to be user defined type)) at least thats what i use

>We use this to get multiple different type of stream results that we want to rebuild on screen. Not just a single type.

this MR doesnt modify anything related to the stream result it instead focuses on unique keys! that we pass in the stream  map
> that should help with your type safety per stream viewmodel you want

even after making this change u still have to do casting every where, once specific place would be onData callback

**Review by FilledStacks — CHANGES_REQUESTED** [review]
My bad, I thought this was for the data type. I've never used a different type of key but that makes sense to have. Please increase the minor version number and set patch to 0 and then add the change into the changelog. 

Make double sure there's no breaking change.

**Comment by Afsal102** [comment]
@FilledStacks haa got it, nothing breaks although i cant update the example haa it doesnt point to the local package path's

**Comment by Afsal102** [comment]
@FilledStacks Bumped the package version!

**Comment by FilledStacks** [comment]
Awesome. Please remove the +0 at the end of the changelog and the version number

**Comment by Eimen2018** [comment]
This will be merged soon

**Comment by Afsal102** [comment]
@Eimen2018 @FilledStacks thanks for making the change haa 🙇

**Comment by FilledStacks** [comment]
This PR broke all existing stacked apps using multi stream viewmodel. I'm reverting until properly tested with backwards compatiblity.

**Comment by Afsal102** [comment]
@FilledStacks ah my bad i think i should have made the commits concise that this would infact be a breaking change. 
A postmortem on why this will be a breaking change!
 - currently the keys are string, this MR will make them an object by default so all the overrides will show syntax errors, to fix this we just have to type the Multiple stream view model with <String>

As for the tests i think no additional tests are needed in my pov! As they wont provide value better than the existing ones( do let me know if u have any suggestions)

**Pull request merged**
